name: Build Rubeus

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore
        run: nuget restore Rubeus.sln

      - name: Build
        run: msbuild Rubeus.sln /p:Configuration=Release /p:Platform="Any CPU"

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Rubeus
          path: |
            **/bin/Release/*.exe